apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-audit-library
  namespace: exalt-shared
  labels:
    app: shared-audit
    component: library
    part-of: exalt-ecosystem
    version: 1.0.0-SNAPSHOT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-audit
  template:
    metadata:
      labels:
        app: shared-audit
        component: library
        part-of: exalt-ecosystem
    spec:
      containers:
      - name: shared-audit
        image: exalt/shared-audit:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health/startup
            port: management
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shared-audit-service
  namespace: exalt-shared
  labels:
    app: shared-audit
    component: library
spec:
  selector:
    app: shared-audit
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP