apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralized-performance-metrics
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
    component: dashboard
    version: v1
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centralized-performance-metrics
  template:
    metadata:
      labels:
        app: centralized-performance-metrics
        component: dashboard
        version: v1
        type: backend
    spec:
      serviceAccountName: centralized-performance-metrics-sa
      containers:
      - name: centralized-performance-metrics
        image: ghcr.io/exalt/centralized-performance-metrics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8105
          name: http
          protocol: TCP
        - containerPort: 8081
          name: management
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8105"
        - name: MANAGEMENT_SERVER_PORT
          value: "8081"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8166"
        - name: EUREKA_SERVER_URL
          value: "http://service-registry:8154/eureka"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: centralized-performance-metrics-db-secret
              key: url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: centralized-performance-metrics-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: centralized-performance-metrics-db-secret
              key: password
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
        resources:
          requests:
            memory: "768Mi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: centralized-performance-metrics-config
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - centralized-performance-metrics
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: centralized-performance-metrics
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
    component: dashboard
    type: backend
spec:
  type: ClusterIP
  ports:
  - port: 8105
    targetPort: http
    protocol: TCP
    name: http
  - port: 8081
    targetPort: management
    protocol: TCP
    name: management
  selector:
    app: centralized-performance-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: centralized-performance-metrics-sa
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: centralized-performance-metrics-config
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
data:
  application.yaml: |
    spring:
      application:
        name: centralized-performance-metrics
      cloud:
        kubernetes:
          reload:
            enabled: true
            mode: polling
            period: 5000
      datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      metrics:
        export:
          prometheus:
            enabled: true
    logging:
      level:
        root: INFO
        com.exalt: DEBUG
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: centralized-performance-metrics-pdb
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: centralized-performance-metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: centralized-performance-metrics-hpa
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: centralized-performance-metrics
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
