apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: centralized-performance-metrics-hpa
  namespace: centralized-dashboard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: centralized-performance-metrics
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
