# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: centralized-performance-metrics-db-secret
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/centralized_performance_metrics_db"
  username: "centralized_performance_metrics_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: centralized-performance-metrics-app-secret
  namespace: centralized-dashboard
  labels:
    app: centralized-performance-metrics
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
  oauth-client-secret: "CHANGE_ME_IN_PRODUCTION"
