apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: centralized-reporting
  namespace: centralized-dashboard
  labels:
    app: centralized-reporting
    component: dashboard
spec:
  selector:
    matchLabels:
      app: centralized-reporting
  endpoints:
  - port: management
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: centralized-reporting-alerts
  namespace: centralized-dashboard
  labels:
    app: centralized-reporting
    component: dashboard
spec:
  groups:
  - name: centralized-reporting.rules
    rules:
    - alert: centralized-reportingDown
      expr: up{job="centralized-reporting"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "centralized-reporting is down"
        description: "centralized-reporting has been down for more than 1 minute."
    
    - alert: centralized-reportingHighMemoryUsage
      expr: (container_memory_usage_bytes{pod=~"centralized-reporting-.*"} / container_spec_memory_limit_bytes) > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "centralized-reporting high memory usage"
        description: "centralized-reporting memory usage is above 90% for more than 5 minutes."
    
    - alert: centralized-reportingHighCPUUsage
      expr: (rate(container_cpu_usage_seconds_total{pod=~"centralized-reporting-.*"}[5m]) / container_spec_cpu_quota) > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "centralized-reporting high CPU usage"
        description: "centralized-reporting CPU usage is above 90% for more than 5 minutes."
