# This is a template for secrets. In production, use sealed secrets or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: centralized-core-db-secret
  namespace: centralized-dashboard
  labels:
    app: centralized-core
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres:5432/centralized_core_db"
  username: "centralized_core_user"
  password: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: centralized-core-app-secret
  namespace: centralized-dashboard
  labels:
    app: centralized-core
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_IN_PRODUCTION"
  api-key: "CHANGE_ME_IN_PRODUCTION"
  encryption-key: "CHANGE_ME_IN_PRODUCTION"
  oauth-client-secret: "CHANGE_ME_IN_PRODUCTION"
